/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfigForm: typeof import('./src/components/common/ConfigForm.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    PicbedSetting: typeof import('./src/components/setting/PicbedSetting.vue')['default']
    PicgoConfigSetting: typeof import('./src/components/setting/PicgoConfigSetting.vue')['default']
    PicGoIndex: typeof import('./src/components/PicGoIndex.vue')['default']
    PicgoPluginSetting: typeof import('./src/components/setting/PicgoPluginSetting.vue')['default']
    PicgoSetting: typeof import('./src/components/PicgoSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
